services:
  - type: web
    name: my_app_render
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s -e production"
    envVars:
      - key: RAILS_ENV
        value: "production"
